name: Build and Deploy Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      id: cache-docker
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/jihyeon2525/chatbot-app .
        docker tag ghcr.io/jihyeon2525/chatbot-app ghcr.io/jihyeon2525/chatbot-app:latest

    - name: Authenticate to GitHub Container Registry
      run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/jihyeon2525/chatbot-app:latest

    - name: SSH into remote server and load Docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASS }}
        port: 22
        script: |
          docker pull ghcr.io/jihyeon2525/chatbot-app:latest
          docker run -d -p 6677:6677 --name chatbot-app ghcr.io/jihyeon2525/chatbot-app:latest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
